from .nodes_latentcutplus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .vae_to_vid import NODE_CLASS_MAPPINGS2, NODE_DISPLAY_NAME_MAPPINGS2

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS','NODE_CLASS_MAPPINGS2', 'NODE_DISPLAY_NAME_MAPPINGS2']
